### ISSUE TITLE
About the parameters of Supplementart Material A

### ISSUE THREAD

**Issue by smallQ-Q** [postBG/DTA.pytorch#12]
Hello professor. Thank you for contributing a so great work.
Here I have a tiny proble~~ :)
In your **supplementary material of DTA**，I saw the experiment of **SVHN→MNIST** and you used backbone of **9 Conv+1 FC**, could you kindly tell me that what's the hyperparameters of the **9 Conv & 1 FC** or you might write it  in your code?
Thank for your help in advance~~
![avatar](D:\Files_Works\VCIS_Files\VCIS_Temp_File\1.png)

**Comment by numpee** [comment]
Hi,

We used the same architecture used by the Self-Ensembling paper. 
You can find the code for this network [here](https://github.com/Britefury/self-ensemble-visual-domain-adapt/blob/master/network_architectures.py#L303).
Also, the architecture is described in page 20 of their paper: https://arxiv.org/pdf/1706.05208.pdf 

:)

**Comment by smallQ-Q** [comment]
Hi professor. I am so sorry to trouble you again~ <br>
Here I am reproducting the experiment of **SVHN→MNIST** which is mentioned in **supplementary material of DTA**. <br>
I remained the **Feature_Extractor_Resnet** and changed the **Classifier** to **9 Conv+1 FC**.<br>
The problem I encountered is that `batch_sizex3x32x32` of input will become a `batch_sizex2048x7x7` of feature_map by Feature_Extractor, but `batch_sizex2048x7x7` of feature_map is too small as a input to **Classfier of 9 Conv+1 FC**. So could professor kindly tell me that how did you do this experiment specifically. Should I change the classifier too?<br>
I’m very grateful~ :)

**Comment by smallQ-Q** [comment]
Hi professor. I am so sorry to trouble you again~ <br>
Here I am reproducting the experiment of **SVHN→MNIST** which is mentioned in **supplementary material of DTA**. <br>
I remained the **Feature_Extractor_Resnet** and changed the **Classifier** to **9 Conv+1 FC**.<br>
The problem I encountered is that `batch_sizex3x32x32` of input will become a `batch_sizex2048x7x7` of feature_map by Feature_Extractor, but `batch_sizex2048x7x7` of feature_map is too small as a input to **Classfier of 9 Conv+1 FC**. So could professor kindly tell me that how did you do this experiment specifically. Should I change the feature_extractor too?<br>
I’m very grateful~ :)
